package shimgen_test

import (
	"strings"
	"testing"

	"github.com/mochilang/mochi-dotnet/metacli"
	"github.com/mochilang/mochi-dotnet/shimgen"
)

// shimFixture creates a minimal Shim for emit tests.
func shimFixture() *shimgen.Shim {
	surface := staticSurface()
	return shimgen.Synth("TestLib", "1.0.0", "net8.0", surface)
}

func TestEmitBridgeCSHeader(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitBridgeCS(s)
	for _, want := range []string{
		"// Bridge.cs -- generated by github.com/mochilang/mochi-dotnet/shimgen; do not edit.",
		"// upstream package: TestLib 1.0.0",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("Bridge.cs missing %q\nfull output:\n%s", want, out)
		}
	}
}

func TestEmitBridgeCSUsings(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitBridgeCS(s)
	for _, want := range []string{
		"using System;",
		"using System.Runtime.InteropServices;",
		"using System.Text;",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("Bridge.cs missing using %q", want)
		}
	}
}

func TestEmitBridgeCSNamespace(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitBridgeCS(s)
	if !strings.Contains(out, "namespace MochiShim.TestLib") {
		t.Errorf("Bridge.cs missing namespace MochiShim.TestLib\nfull:\n%s", out)
	}
}

func TestEmitBridgeCSMochiString(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitBridgeCS(s)
	for _, want := range []string{
		"public struct MochiString",
		"public byte* Ptr;",
		"public int   Len;",
		"MochiStringToManaged",
		"MochiStringFromManaged",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("Bridge.cs missing %q", want)
		}
	}
}

func TestEmitBridgeCSMarshalFree(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitBridgeCS(s)
	if !strings.Contains(out, `[UnmanagedCallersOnly(EntryPoint = "mochi_marshal_free")]`) {
		t.Errorf("Bridge.cs missing MarshalFree attribute\nfull:\n%s", out)
	}
	if !strings.Contains(out, "public static void MarshalFree(nint ptr)") {
		t.Errorf("Bridge.cs missing MarshalFree method\nfull:\n%s", out)
	}
}

func TestEmitBridgeCSUnmanagedCallersOnly(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitBridgeCS(s)
	for _, m := range s.Methods {
		want := `[UnmanagedCallersOnly(EntryPoint = "` + m.EntryPoint + `")]`
		if !strings.Contains(out, want) {
			t.Errorf("Bridge.cs missing attribute for %s:\n  want: %s\nfull:\n%s",
				m.EntryPoint, want, out)
		}
	}
}

func TestEmitBridgeCSUnsafeClass(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitBridgeCS(s)
	if !strings.Contains(out, "public static unsafe class Bridge") {
		t.Errorf("Bridge.cs missing 'public static unsafe class Bridge'")
	}
}

func TestEmitBridgeCSNamespaceDotted(t *testing.T) {
	surface := &metacli.ApiSurface{
		Types: []metacli.SurfaceType{},
	}
	s := shimgen.Synth("Newtonsoft.Json", "13.0.3", "net8.0", surface)
	out := shimgen.EmitBridgeCS(s)
	// Dots should be removed from namespace.
	if strings.Contains(out, "namespace MochiShim.Newtonsoft.Json") {
		t.Errorf("Bridge.cs namespace should not have dots from package name")
	}
	if !strings.Contains(out, "namespace MochiShim.NewtonsoftJson") {
		t.Errorf("Bridge.cs missing MochiShim.NewtonsoftJson namespace\nfull:\n%s", out)
	}
}

func TestEmitBridgeCSStringReturn(t *testing.T) {
	surface := &metacli.ApiSurface{
		Types: []metacli.SurfaceType{
			{
				FullName:  "Demo.Util",
				ShortName: "Util",
				Namespace: "Demo",
				Kind:      metacli.KindClass,
				IsStatic:  true,
				Methods: []metacli.SurfaceMethod{
					{
						Name:     "Greet",
						IsStatic: true,
						ReturnType: metacli.TypeRef{
							FullName: "System.String",
							Kind:     metacli.TypeRefPrimitive,
						},
						Params: []metacli.ParamDef{
							{Name: "name", Type: metacli.TypeRef{FullName: "System.String", Kind: metacli.TypeRefPrimitive}},
						},
					},
				},
			},
		},
	}
	s := shimgen.Synth("Demo", "1.0.0", "net8.0", surface)
	out := shimgen.EmitBridgeCS(s)
	// String return should produce MochiString return type.
	if !strings.Contains(out, "MochiString") {
		t.Errorf("string return method should use MochiString type\nfull:\n%s", out)
	}
	if !strings.Contains(out, "MochiStringFromManaged") {
		t.Errorf("string return method should call MochiStringFromManaged\nfull:\n%s", out)
	}
}

func TestEmitCsprojTargetFramework(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitCsproj(s)
	if !strings.Contains(out, "<TargetFramework>net8.0</TargetFramework>") {
		t.Errorf("csproj missing TargetFramework\nfull:\n%s", out)
	}
}

func TestEmitCsprojAllowUnsafeBlocks(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitCsproj(s)
	if !strings.Contains(out, "<AllowUnsafeBlocks>true</AllowUnsafeBlocks>") {
		t.Errorf("csproj missing AllowUnsafeBlocks\nfull:\n%s", out)
	}
}

func TestEmitCsprojPackageReference(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitCsproj(s)
	if !strings.Contains(out, `Include="TestLib"`) {
		t.Errorf("csproj missing PackageReference Include\nfull:\n%s", out)
	}
	if !strings.Contains(out, `Version="[1.0.0]"`) {
		t.Errorf("csproj missing pinned Version\nfull:\n%s", out)
	}
}

func TestEmitCsprojNullable(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitCsproj(s)
	if !strings.Contains(out, "<Nullable>enable</Nullable>") {
		t.Errorf("csproj missing Nullable=enable")
	}
}

func TestEmitCsprojImplicitUsings(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitCsproj(s)
	if !strings.Contains(out, "<ImplicitUsings>disable</ImplicitUsings>") {
		t.Errorf("csproj missing ImplicitUsings=disable")
	}
}

func TestEmitCsprojAssemblyName(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitCsproj(s)
	if !strings.Contains(out, "<AssemblyName>MochiShim.TestLib</AssemblyName>") {
		t.Errorf("csproj missing AssemblyName\nfull:\n%s", out)
	}
}

func TestEmitSkippedTXTEmpty(t *testing.T) {
	s := &shimgen.Shim{}
	out := shimgen.EmitSkippedTXT(s)
	if out != "# No skipped items.\n" {
		t.Errorf("empty SKIPPED.txt = %q; want '# No skipped items.'", out)
	}
}

func TestEmitSkippedTXTFormat(t *testing.T) {
	s := shimFixture()
	out := shimgen.EmitSkippedTXT(s)
	// Should have at least one group since UnsafeOp is skipped.
	if !strings.Contains(out, "# SkipPointer") {
		t.Errorf("SKIPPED.txt missing # SkipPointer group\nfull:\n%s", out)
	}
	if !strings.Contains(out, "SKIPPED: ") {
		t.Errorf("SKIPPED.txt missing SKIPPED: lines\nfull:\n%s", out)
	}
	if !strings.Contains(out, "Reason: SkipPointer") {
		t.Errorf("SKIPPED.txt missing Reason: SkipPointer\nfull:\n%s", out)
	}
}

func TestEmitDeterministic(t *testing.T) {
	s := shimFixture()
	first := shimgen.EmitBridgeCS(s)
	for range 5 {
		got := shimgen.EmitBridgeCS(s)
		if got != first {
			t.Error("EmitBridgeCS non-deterministic")
		}
	}
}

func TestEmitCsprojDeterministic(t *testing.T) {
	s := shimFixture()
	first := shimgen.EmitCsproj(s)
	for range 5 {
		if shimgen.EmitCsproj(s) != first {
			t.Error("EmitCsproj non-deterministic")
		}
	}
}
