package shimgen

import (
	"fmt"
	"sort"
	"strings"
	"unicode"

	"github.com/mochilang/mochi-dotnet/errors"
	"github.com/mochilang/mochi-dotnet/typemap"
)

// EmitBridgeCS renders Bridge.cs, the C# source file containing all
// [UnmanagedCallersOnly] methods for the shim project.
func EmitBridgeCS(s *Shim) string {
	var b strings.Builder
	ns := safeNamespace(s.Package)

	b.WriteString("// Bridge.cs -- generated by github.com/mochilang/mochi-dotnet/shimgen; do not edit.\n")
	fmt.Fprintf(&b, "// upstream package: %s %s\n", s.Package, s.PackageVersion)
	b.WriteString("using System;\n")
	b.WriteString("using System.Runtime.InteropServices;\n")
	b.WriteString("using System.Text;\n")

	// Emit any extra usings needed for GCHandle.
	if needsGCHandle(s) {
		b.WriteString("using System.Runtime.CompilerServices;\n")
	}

	b.WriteString("\n")
	fmt.Fprintf(&b, "namespace MochiShim.%s\n", ns)
	b.WriteString("{\n")
	b.WriteString("    public static unsafe class Bridge\n")
	b.WriteString("    {\n")

	// MochiString struct and helpers.
	b.WriteString("        // MochiString: UTF-8 string passed as pointer + byte count.\n")
	b.WriteString("        // The caller owns the memory; use MarshalFree to release.\n")
	b.WriteString("        [StructLayout(LayoutKind.Sequential)]\n")
	b.WriteString("        public struct MochiString\n")
	b.WriteString("        {\n")
	b.WriteString("            public byte* Ptr;\n")
	b.WriteString("            public int   Len;\n")
	b.WriteString("        }\n")
	b.WriteString("\n")
	b.WriteString("        // MochiStringToManaged converts a MochiString to a managed string.\n")
	b.WriteString("        private static string MochiStringToManaged(MochiString s)\n")
	b.WriteString("            => s.Ptr == null ? string.Empty\n")
	b.WriteString("             : Encoding.UTF8.GetString(s.Ptr, s.Len);\n")
	b.WriteString("\n")
	b.WriteString("        // MochiStringFromManaged encodes a managed string to a MochiString.\n")
	b.WriteString("        // The caller must free with MarshalFree.\n")
	b.WriteString("        private static MochiString MochiStringFromManaged(string? s)\n")
	b.WriteString("        {\n")
	b.WriteString("            if (s == null) return default;\n")
	b.WriteString("            var bytes = Encoding.UTF8.GetBytes(s);\n")
	b.WriteString("            var ptr = (byte*)Marshal.AllocCoTaskMem(bytes.Length);\n")
	b.WriteString("            bytes.AsSpan().CopyTo(new Span<byte>(ptr, bytes.Length));\n")
	b.WriteString("            return new MochiString { Ptr = ptr, Len = bytes.Length };\n")
	b.WriteString("        }\n")
	b.WriteString("\n")
	b.WriteString("        [UnmanagedCallersOnly(EntryPoint = \"mochi_marshal_free\")]\n")
	b.WriteString("        public static void MarshalFree(nint ptr) => Marshal.FreeCoTaskMem(ptr);\n")
	b.WriteString("\n")
	b.WriteString("        // --- generated methods ---\n")

	for _, m := range s.Methods {
		b.WriteString("\n")
		emitBridgeMethod(&b, &m)
	}

	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}

// emitBridgeMethod renders a single [UnmanagedCallersOnly] method.
func emitBridgeMethod(b *strings.Builder, m *ShimMethod) {
	if m.DocComment != "" {
		fmt.Fprintf(b, "        // %s\n", m.DocComment)
	}
	fmt.Fprintf(b, "        [UnmanagedCallersOnly(EntryPoint = %q)]\n", m.EntryPoint)

	// Build the FFI return type.
	retFFI := ffiReturnType(m)

	// Build the param list.
	paramDecls := make([]string, 0, len(m.Params))
	for _, p := range m.Params {
		paramDecls = append(paramDecls, ffiParamDecl(p))
	}

	fmt.Fprintf(b, "        public static %s %s(%s)\n",
		retFFI, m.CSMethodName, strings.Join(paramDecls, ", "))
	b.WriteString("        {\n")

	emitBridgeBody(b, m)

	b.WriteString("        }\n")
}

// ffiReturnType returns the C#-FFI-compatible return type string for a method.
func ffiReturnType(m *ShimMethod) string {
	if m.Return == nil {
		return "void"
	}
	switch m.Return.Kind {
	case typemap.KindString, typemap.KindBytes:
		return "MochiString"
	case typemap.KindBool:
		return "byte"
	case typemap.KindHandle, typemap.KindRecord:
		return "nint"
	case typemap.KindList, typemap.KindMap, typemap.KindSet:
		return "nint"
	default:
		return m.Return.FFIRepr()
	}
}

// ffiParamDecl renders a single parameter declaration for an FFI method.
func ffiParamDecl(p ShimParam) string {
	switch p.Mapping.Kind {
	case typemap.KindString, typemap.KindBytes:
		return "MochiString " + p.Name
	case typemap.KindBool:
		return "byte " + p.Name
	case typemap.KindHandle, typemap.KindRecord:
		return "nint " + p.Name
	case typemap.KindList, typemap.KindMap, typemap.KindSet:
		return "nint " + p.Name
	default:
		return p.Mapping.FFIRepr() + " " + p.Name
	}
}

// emitBridgeBody renders the method body with appropriate marshalling.
func emitBridgeBody(b *strings.Builder, m *ShimMethod) {
	// Check for compound types that are not yet fully supported.
	if hasCompoundParam(m) || isCompoundReturn(m) {
		b.WriteString("            // TODO: compound marshal (phase 11)\n")
		b.WriteString("            throw new NotImplementedException(\"compound marshal not yet implemented in v1\");\n")
		return
	}

	// Marshal string/bool params from FFI.
	managedArgs := make([]string, 0, len(m.Params))
	for _, p := range m.Params {
		switch p.Mapping.Kind {
		case typemap.KindString:
			managed := "__managed_" + p.Name
			fmt.Fprintf(b, "            var %s = MochiStringToManaged(%s);\n", managed, p.Name)
			managedArgs = append(managedArgs, managed)
		case typemap.KindBool:
			managed := "__managed_" + p.Name
			fmt.Fprintf(b, "            var %s = %s != 0;\n", managed, p.Name)
			managedArgs = append(managedArgs, managed)
		case typemap.KindHandle, typemap.KindRecord:
			managed := "__managed_" + p.Name
			clrType := p.Mapping.HandleName
			if clrType == "" {
				clrType = p.Mapping.CLRName
			}
			fmt.Fprintf(b, "            var %s = (%s)GCHandle.FromIntPtr(%s).Target!;\n",
				managed, clrType, p.Name)
			managedArgs = append(managedArgs, managed)
		default:
			managedArgs = append(managedArgs, p.Name)
		}
	}

	// Build the call expression.
	callExpr := m.UpstreamCall + "(" + strings.Join(managedArgs, ", ") + ")"
	if m.IsAsync {
		callExpr = callExpr + ".GetAwaiter().GetResult()"
	}

	// Emit the call and marshal the return.
	if m.Return == nil {
		fmt.Fprintf(b, "            %s;\n", callExpr)
		return
	}

	switch m.Return.Kind {
	case typemap.KindString:
		fmt.Fprintf(b, "            var __result = %s;\n", callExpr)
		b.WriteString("            return MochiStringFromManaged(__result);\n")
	case typemap.KindBool:
		fmt.Fprintf(b, "            var __result = %s;\n", callExpr)
		b.WriteString("            return __result ? (byte)1 : (byte)0;\n")
	case typemap.KindHandle, typemap.KindRecord:
		fmt.Fprintf(b, "            var __result = %s;\n", callExpr)
		b.WriteString("            return GCHandle.ToIntPtr(GCHandle.Alloc(__result, GCHandleType.Normal));\n")
	default:
		fmt.Fprintf(b, "            return %s;\n", callExpr)
	}
}

// hasCompoundParam reports whether any parameter is a compound type not
// handled by simple marshalling.
func hasCompoundParam(m *ShimMethod) bool {
	for _, p := range m.Params {
		switch p.Mapping.Kind {
		case typemap.KindList, typemap.KindMap, typemap.KindSet,
			typemap.KindTuple, typemap.KindOption:
			return true
		}
	}
	return false
}

// isCompoundReturn reports whether the return type is a compound type not
// handled by simple marshalling.
func isCompoundReturn(m *ShimMethod) bool {
	if m.Return == nil {
		return false
	}
	switch m.Return.Kind {
	case typemap.KindList, typemap.KindMap, typemap.KindSet,
		typemap.KindTuple, typemap.KindOption:
		return true
	}
	return false
}

// needsGCHandle reports whether the shim needs GCHandle support.
func needsGCHandle(s *Shim) bool {
	for _, m := range s.Methods {
		if m.Return != nil {
			switch m.Return.Kind {
			case typemap.KindHandle, typemap.KindRecord:
				return true
			}
		}
		for _, p := range m.Params {
			switch p.Mapping.Kind {
			case typemap.KindHandle, typemap.KindRecord:
				return true
			}
		}
	}
	return false
}

// safeNamespace converts a NuGet package id to a safe C# namespace segment.
// "Newtonsoft.Json" -> "NewtonsoftJson"
func safeNamespace(pkg string) string {
	var b strings.Builder
	for _, r := range pkg {
		switch {
		case r == '.', r == '-':
			// skip separators
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

// EmitCsproj renders the .csproj for the shim project.
func EmitCsproj(s *Shim) string {
	ns := safeNamespace(s.Package)
	var b strings.Builder
	b.WriteString("<Project Sdk=\"Microsoft.NET.Sdk\">\n")
	b.WriteString("  <PropertyGroup>\n")
	fmt.Fprintf(&b, "    <TargetFramework>%s</TargetFramework>\n", s.TargetFramework)
	b.WriteString("    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>\n")
	b.WriteString("    <PublishAot>false</PublishAot>\n")
	b.WriteString("    <Nullable>enable</Nullable>\n")
	b.WriteString("    <ImplicitUsings>disable</ImplicitUsings>\n")
	fmt.Fprintf(&b, "    <AssemblyName>MochiShim.%s</AssemblyName>\n", ns)
	b.WriteString("  </PropertyGroup>\n")
	b.WriteString("  <ItemGroup>\n")
	fmt.Fprintf(&b, "    <PackageReference Include=%q Version=%q />\n",
		s.Package, "["+s.PackageVersion+"]")
	b.WriteString("  </ItemGroup>\n")
	b.WriteString("</Project>\n")
	return b.String()
}

// EmitSkippedTXT renders SKIPPED.txt in the same format as the rust wrapper.
// Groups are sorted by SkipReason name; within each group entries are sorted
// by ItemPath.
func EmitSkippedTXT(s *Shim) string {
	if len(s.Skipped) == 0 {
		return "# No skipped items.\n"
	}
	groups := map[errors.SkipReason][]errors.SkipReport{}
	for _, sr := range s.Skipped {
		groups[sr.Reason] = append(groups[sr.Reason], sr)
	}
	keys := make([]errors.SkipReason, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i].String() < keys[j].String() })
	var b strings.Builder
	for _, k := range keys {
		entries := groups[k]
		sort.Slice(entries, func(i, j int) bool { return entries[i].ItemPath < entries[j].ItemPath })
		b.WriteString("# ")
		b.WriteString(k.String())
		b.WriteString("\n")
		for _, e := range entries {
			b.WriteString(e.String())
		}
		b.WriteString("\n")
	}
	return b.String()
}
