package emit

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mochilang/mochi-dotnet/shimgen"
)

// Files is the bundle of Mochi-side source files for one NuGet package.
type Files struct {
	// ExternMochi is the body of <pkg>_extern.mochi -- extern type + extern fun declarations.
	ExternMochi string
	// AliasMochi is the body of <pkg>.mochi -- user-facing re-exports.
	AliasMochi string
}

// Emit produces the Mochi-side source files from a shimgen.Shim.
func Emit(s *shimgen.Shim) Files {
	return Files{
		ExternMochi: emitExtern(s),
		AliasMochi:  emitAlias(s),
	}
}

func emitExtern(s *shimgen.Shim) string {
	var b strings.Builder
	writeHeader(&b, s, "extern bindings")
	b.WriteString("\n")

	// Collect and emit all extern type declarations.
	names := collectTypeNames(s)
	for _, name := range names {
		b.WriteString("extern type ")
		b.WriteString(name)
		b.WriteString("\n")
	}
	if len(s.Methods) == 0 {
		return b.String()
	}
	if len(names) > 0 {
		b.WriteString("\n")
	}
	for _, m := range s.Methods {
		b.WriteString(emitExternFn(m))
		b.WriteString("\n")
	}
	return b.String()
}

func emitAlias(s *shimgen.Shim) string {
	var b strings.Builder
	writeHeader(&b, s, "alias module")
	b.WriteString("\n")
	for _, m := range s.Methods {
		b.WriteString(emitAliasFn(m))
		b.WriteString("\n")
	}
	return b.String()
}

func writeHeader(b *strings.Builder, s *shimgen.Shim, kind string) {
	b.WriteString("// ")
	b.WriteString(kind)
	b.WriteString(" for ")
	b.WriteString(s.Package)
	b.WriteString(" ")
	b.WriteString(s.PackageVersion)
	b.WriteString("\n")
	b.WriteString("// generated by github.com/mochilang/mochi-dotnet/emit; do not edit.\n")
}

func emitExternFn(m shimgen.ShimMethod) string {
	var b strings.Builder
	b.WriteString("extern fun ")
	b.WriteString(m.EntryPoint)
	b.WriteString("(")
	parts := make([]string, 0, len(m.Params))
	for _, p := range m.Params {
		parts = append(parts, fmt.Sprintf("%s: %s", p.Name, MochiRender(&p.Mapping)))
	}
	b.WriteString(strings.Join(parts, ", "))
	b.WriteString(")")
	if m.Return != nil {
		b.WriteString(": ")
		b.WriteString(MochiRender(m.Return))
	}
	b.WriteString("\n")
	return b.String()
}

// emitAliasFn renders the user-facing re-export wrapper function.
// The alias name is derived from the CSMethodName (which is already
// "TypeShortName_MethodName"). We use the last segment after the final
// underscore as the short name when the method name is clear, but since
// CSMethodName encodes both type and method, we expose the full CSMethodName
// with proper casing as the alias.
func emitAliasFn(m shimgen.ShimMethod) string {
	short := m.CSMethodName
	var b strings.Builder
	b.WriteString("fun ")
	b.WriteString(short)
	b.WriteString("(")
	parts := make([]string, 0, len(m.Params))
	args := make([]string, 0, len(m.Params))
	for _, p := range m.Params {
		parts = append(parts, fmt.Sprintf("%s: %s", p.Name, MochiRender(&p.Mapping)))
		args = append(args, p.Name)
	}
	b.WriteString(strings.Join(parts, ", "))
	b.WriteString(")")
	if m.Return != nil {
		b.WriteString(": ")
		b.WriteString(MochiRender(m.Return))
	}
	b.WriteString(" {\n")
	call := fmt.Sprintf("%s(%s)", m.EntryPoint, strings.Join(args, ", "))
	if m.Return != nil {
		b.WriteString("  return ")
		b.WriteString(call)
		b.WriteString("\n")
	} else {
		b.WriteString("  ")
		b.WriteString(call)
		b.WriteString("\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// collectTypeNames walks every Mapping in the shim and returns the sorted,
// deduplicated list of handle/record/enum type names that need `extern type`
// declarations.
func collectTypeNames(s *shimgen.Shim) []string {
	seen := map[string]struct{}{}
	for _, m := range s.Methods {
		for _, p := range m.Params {
			for _, n := range typeNames(&p.Mapping) {
				seen[n] = struct{}{}
			}
		}
		if m.Return != nil {
			for _, n := range typeNames(m.Return) {
				seen[n] = struct{}{}
			}
		}
	}
	out := make([]string, 0, len(seen))
	for n := range seen {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}
