package emit_test

import (
	"strings"
	"testing"

	"github.com/mochilang/mochi-dotnet/metacli"
	"github.com/mochilang/mochi-dotnet/emit"
	"github.com/mochilang/mochi-dotnet/shimgen"
	"github.com/mochilang/mochi-dotnet/typemap"
)

// jsonLikeSurface builds a shimgen.Shim that mirrors a minimal Newtonsoft.Json
// subset. We build the Shim directly (bypassing Synth) to control exact field
// values.
func jsonLikeShim() *shimgen.Shim {
	stringMapping := &typemap.Mapping{
		Kind:      typemap.KindString,
		CLRName:   "System.String",
		MochiType: "string",
	}
	handleMapping := &typemap.Mapping{
		Kind:       typemap.KindHandle,
		CLRName:    "Newtonsoft.Json.JsonConvert",
		MochiType:  "JsonConvert",
		HandleName: "JsonConvert",
	}
	intMapping := &typemap.Mapping{
		Kind:      typemap.KindInt,
		CLRName:   "System.Int32",
		MochiType: "int",
	}
	return &shimgen.Shim{
		Package:         "Newtonsoft.Json",
		PackageVersion:  "13.0.3",
		TargetFramework: "net8.0",
		Methods: []shimgen.ShimMethod{
			{
				EntryPoint:   "mochi_newtonsoftjson_jsonconvert_serializeobject",
				CSMethodName: "JsonConvert_SerializeObject",
				UpstreamCall: "Newtonsoft.Json.JsonConvert.SerializeObject",
				Params: []shimgen.ShimParam{
					{Name: "value", Mapping: *stringMapping},
				},
				Return:   stringMapping,
				IsStatic: true,
			},
			{
				EntryPoint:   "mochi_newtonsoftjson_jsonconvert_deserializeobject",
				CSMethodName: "JsonConvert_DeserializeObject",
				UpstreamCall: "Newtonsoft.Json.JsonConvert.DeserializeObject",
				Params: []shimgen.ShimParam{
					{Name: "json", Mapping: *stringMapping},
				},
				Return:   handleMapping,
				IsStatic: true,
			},
			{
				EntryPoint:   "mochi_newtonsoftjson_jsonconvert_getversion",
				CSMethodName: "JsonConvert_GetVersion",
				UpstreamCall: "Newtonsoft.Json.JsonConvert.GetVersion",
				Params:       nil,
				Return:       intMapping,
				IsStatic:     true,
			},
		},
	}
}

func TestEmitExternHeader(t *testing.T) {
	s := jsonLikeShim()
	f := emit.Emit(s)
	for _, want := range []string{
		"// extern bindings for Newtonsoft.Json 13.0.3",
		"// generated by github.com/mochilang/mochi-dotnet/emit; do not edit.",
	} {
		if !strings.Contains(f.ExternMochi, want) {
			t.Errorf("ExternMochi missing %q\nfull:\n%s", want, f.ExternMochi)
		}
	}
}

func TestEmitAliasHeader(t *testing.T) {
	s := jsonLikeShim()
	f := emit.Emit(s)
	for _, want := range []string{
		"// alias module for Newtonsoft.Json 13.0.3",
		"// generated by github.com/mochilang/mochi-dotnet/emit; do not edit.",
	} {
		if !strings.Contains(f.AliasMochi, want) {
			t.Errorf("AliasMochi missing %q\nfull:\n%s", want, f.AliasMochi)
		}
	}
}

func TestEmitExternFnSignatures(t *testing.T) {
	s := jsonLikeShim()
	f := emit.Emit(s)
	for _, want := range []string{
		"extern fun mochi_newtonsoftjson_jsonconvert_serializeobject(value: string): string",
		"extern fun mochi_newtonsoftjson_jsonconvert_deserializeobject(json: string): JsonConvert",
		"extern fun mochi_newtonsoftjson_jsonconvert_getversion(): int",
	} {
		if !strings.Contains(f.ExternMochi, want) {
			t.Errorf("ExternMochi missing %q\nfull:\n%s", want, f.ExternMochi)
		}
	}
}

func TestEmitExternTypeDeclarations(t *testing.T) {
	s := jsonLikeShim()
	f := emit.Emit(s)
	if !strings.Contains(f.ExternMochi, "extern type JsonConvert") {
		t.Errorf("ExternMochi missing 'extern type JsonConvert'\nfull:\n%s", f.ExternMochi)
	}
	// extern type must precede extern fun.
	typeIdx := strings.Index(f.ExternMochi, "extern type JsonConvert")
	fnIdx := strings.Index(f.ExternMochi, "extern fun ")
	if typeIdx < 0 || fnIdx < 0 {
		t.Fatalf("missing extern type or extern fun in output")
	}
	if typeIdx > fnIdx {
		t.Errorf("extern type must precede extern fun (typeIdx=%d fnIdx=%d)", typeIdx, fnIdx)
	}
}

func TestEmitAliasFnWrappers(t *testing.T) {
	s := jsonLikeShim()
	f := emit.Emit(s)
	for _, want := range []string{
		"fun JsonConvert_SerializeObject(value: string): string {",
		"  return mochi_newtonsoftjson_jsonconvert_serializeobject(value)",
		"fun JsonConvert_DeserializeObject(json: string): JsonConvert {",
		"  return mochi_newtonsoftjson_jsonconvert_deserializeobject(json)",
		"fun JsonConvert_GetVersion(): int {",
		"  return mochi_newtonsoftjson_jsonconvert_getversion()",
	} {
		if !strings.Contains(f.AliasMochi, want) {
			t.Errorf("AliasMochi missing %q\nfull:\n%s", want, f.AliasMochi)
		}
	}
}

func TestEmitVoidReturn(t *testing.T) {
	s := &shimgen.Shim{
		Package:        "Demo",
		PackageVersion: "0.1.0",
		Methods: []shimgen.ShimMethod{
			{
				EntryPoint:   "mochi_demo_util_reset",
				CSMethodName: "Util_Reset",
				UpstreamCall: "Demo.Util.Reset",
				Params:       nil,
				Return:       nil,
				IsStatic:     true,
			},
		},
	}
	f := emit.Emit(s)
	if !strings.Contains(f.ExternMochi, "extern fun mochi_demo_util_reset()\n") {
		t.Errorf("ExternMochi unit-return shape wrong:\n%s", f.ExternMochi)
	}
	if !strings.Contains(f.AliasMochi, "fun Util_Reset() {\n  mochi_demo_util_reset()\n}\n") {
		t.Errorf("AliasMochi unit-return body wrong:\n%s", f.AliasMochi)
	}
}

func TestEmitNoMethods(t *testing.T) {
	s := &shimgen.Shim{Package: "Empty", PackageVersion: "0.0.0"}
	f := emit.Emit(s)
	if !strings.Contains(f.ExternMochi, "// extern bindings for Empty 0.0.0") {
		t.Errorf("ExternMochi missing header for empty shim")
	}
	if strings.Contains(f.ExternMochi, "extern fun ") {
		t.Errorf("empty shim should have no extern fun lines")
	}
	if strings.Contains(f.ExternMochi, "extern type ") {
		t.Errorf("empty shim should have no extern type lines")
	}
}

func TestEmitDeterministic(t *testing.T) {
	s := jsonLikeShim()
	first := emit.Emit(s)
	for range 5 {
		got := emit.Emit(s)
		if got.ExternMochi != first.ExternMochi {
			t.Error("ExternMochi non-deterministic")
		}
		if got.AliasMochi != first.AliasMochi {
			t.Error("AliasMochi non-deterministic")
		}
	}
}

func TestEmitMochiRenderScalars(t *testing.T) {
	cases := []struct {
		mapping *typemap.Mapping
		want    string
	}{
		{&typemap.Mapping{Kind: typemap.KindBool}, "bool"},
		{&typemap.Mapping{Kind: typemap.KindByte}, "byte"},
		{&typemap.Mapping{Kind: typemap.KindInt}, "int"},
		{&typemap.Mapping{Kind: typemap.KindInt64}, "int64"},
		{&typemap.Mapping{Kind: typemap.KindUInt}, "uint"},
		{&typemap.Mapping{Kind: typemap.KindUInt64}, "uint64"},
		{&typemap.Mapping{Kind: typemap.KindFloat}, "float"},
		{&typemap.Mapping{Kind: typemap.KindFloat64}, "float64"},
		{&typemap.Mapping{Kind: typemap.KindChar}, "char"},
		{&typemap.Mapping{Kind: typemap.KindString}, "string"},
		{&typemap.Mapping{Kind: typemap.KindBytes}, "bytes"},
		{&typemap.Mapping{Kind: typemap.KindUnit}, "()"},
	}
	for _, c := range cases {
		got := emit.MochiRender(c.mapping)
		if got != c.want {
			t.Errorf("MochiRender(%v) = %q; want %q", c.mapping.Kind, got, c.want)
		}
	}
}

func TestEmitMochiRenderHandle(t *testing.T) {
	m := &typemap.Mapping{Kind: typemap.KindHandle, HandleName: "MyClass"}
	if got := emit.MochiRender(m); got != "MyClass" {
		t.Errorf("MochiRender(handle) = %q; want MyClass", got)
	}
}

func TestEmitMochiRenderEnum(t *testing.T) {
	m := &typemap.Mapping{Kind: typemap.KindEnum, HandleName: "MyEnum"}
	if got := emit.MochiRender(m); got != "MyEnum_enum" {
		t.Errorf("MochiRender(enum) = %q; want MyEnum_enum", got)
	}
}

func TestEmitMochiRenderList(t *testing.T) {
	inner := &typemap.Mapping{Kind: typemap.KindString}
	m := &typemap.Mapping{Kind: typemap.KindList, Elem: inner}
	if got := emit.MochiRender(m); got != "list<string>" {
		t.Errorf("MochiRender(list<string>) = %q", got)
	}
}

func TestEmitMochiRenderMap(t *testing.T) {
	k := &typemap.Mapping{Kind: typemap.KindString}
	v := &typemap.Mapping{Kind: typemap.KindInt}
	m := &typemap.Mapping{Kind: typemap.KindMap, Key: k, Value: v}
	if got := emit.MochiRender(m); got != "map<string, int>" {
		t.Errorf("MochiRender(map<string,int>) = %q", got)
	}
}

func TestEmitMochiRenderOption(t *testing.T) {
	inner := &typemap.Mapping{Kind: typemap.KindInt}
	m := &typemap.Mapping{Kind: typemap.KindOption, Elem: inner}
	if got := emit.MochiRender(m); got != "option<int>" {
		t.Errorf("MochiRender(option<int>) = %q", got)
	}
}

func TestEmitMochiRenderAsync(t *testing.T) {
	inner := &typemap.Mapping{Kind: typemap.KindString}
	m := &typemap.Mapping{Kind: typemap.KindTask, Inner: inner}
	if got := emit.MochiRender(m); got != "async<string>" {
		t.Errorf("MochiRender(async<string>) = %q", got)
	}
}

func TestEmitMochiRenderAsyncUnit(t *testing.T) {
	inner := &typemap.Mapping{Kind: typemap.KindUnit}
	m := &typemap.Mapping{Kind: typemap.KindTask, Inner: inner}
	if got := emit.MochiRender(m); got != "async" {
		t.Errorf("MochiRender(async<unit>) = %q; want async", got)
	}
}

func TestEmitMochiRenderTuple(t *testing.T) {
	m := &typemap.Mapping{
		Kind: typemap.KindTuple,
		Fields: []typemap.Mapping{
			{Kind: typemap.KindInt},
			{Kind: typemap.KindString},
		},
	}
	if got := emit.MochiRender(m); got != "(int, string)" {
		t.Errorf("MochiRender(tuple) = %q; want (int, string)", got)
	}
}

func TestEmitMochiRenderNil(t *testing.T) {
	if got := emit.MochiRender(nil); got != "()" {
		t.Errorf("MochiRender(nil) = %q; want ()", got)
	}
}

// TestEmitFromSynth exercises Emit fed by Synth to verify end-to-end correctness.
func TestEmitFromSynth(t *testing.T) {
	surface := &metacli.ApiSurface{
		Assembly:        "CalcLib",
		Version:         "2.0.0",
		TargetFramework: "net8.0",
		Types: []metacli.SurfaceType{
			{
				FullName:  "CalcLib.Math",
				ShortName: "Math",
				Namespace: "CalcLib",
				Kind:      metacli.KindClass,
				IsStatic:  true,
				Methods: []metacli.SurfaceMethod{
					{
						Name:     "Add",
						IsStatic: true,
						ReturnType: metacli.TypeRef{
							FullName: "System.Int32",
							Kind:     metacli.TypeRefPrimitive,
						},
						Params: []metacli.ParamDef{
							{Name: "a", Type: metacli.TypeRef{FullName: "System.Int32", Kind: metacli.TypeRefPrimitive}},
							{Name: "b", Type: metacli.TypeRef{FullName: "System.Int32", Kind: metacli.TypeRefPrimitive}},
						},
					},
				},
			},
		},
	}
	s := shimgen.Synth("CalcLib", "2.0.0", "net8.0", surface)
	f := emit.Emit(s)

	if !strings.Contains(f.ExternMochi, "extern fun") {
		t.Errorf("ExternMochi missing extern fun\nfull:\n%s", f.ExternMochi)
	}
	if !strings.Contains(f.AliasMochi, "fun Math_Add") {
		t.Errorf("AliasMochi missing fun Math_Add\nfull:\n%s", f.AliasMochi)
	}
	if !strings.Contains(f.AliasMochi, "a: int, b: int") {
		t.Errorf("AliasMochi missing params 'a: int, b: int'\nfull:\n%s", f.AliasMochi)
	}
}
